### ISSUE TITLE
Update master branch with the version harness-delegate-ng-1.0.18.tgz

### ISSUE THREAD

**Issue by mmorejon** [harness/delegate-helm-chart#82]
Could you merge the version harness-delegate-ng-1.0.18.tgz in the main branch? 🙏 

[artifacthub.io](https://artifacthub.io/packages/helm/delegate/harness-delegate-ng)
![image](https://github.com/harness/delegate-helm-chart/assets/5578317/84387487-9cba-48e7-9881-02b0226e60e5)

**Comment by djsly** [comment]
I dont see it reflected in artifactory hub, are you missing a step ?
